# python_concurrency_with_asyncio
Изучение Asyncio по книге "Asyncio и конкурентное программирование на Python" MATTHEW FOWLER


Потенциальная проблема в **create_task_2** заключается в том, что задача может работать неопределенно долго. 
В рассмотренных примерах если бы задачи работали вечно, то мы бы застряли в предложении await без всякой обратной связи. 
И остановить бы программу не смогли, даже если бы захотели. 
В библиотеке asyncio предусмотрены обе ситуации – мы можем снять задачу или задать тайм-аут.

У каждого объекта задачи есть метод cancel, который можно вызвать, если требуется остановить задачу. 
В результате снятия задача возбудит исключение CancelledError, когда мы ждем ее с помощью await. 
Пример в файле cancelled_task
